"use client";
import { useState, useEffect, useRef } from "react";
const Icon = {
  fix: () => (<svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M14.7 6.3a1 1 0 000 1.4l1.6 1.6a1 1 0 001.4 0l3.77-3.77a6 6 0 01-7.94 7.94l-6.91 6.91a2.12 2.12 0 01-3-3l6.91-6.91a6 6 0 017.94-7.94l-3.76 3.76z" /></svg>),
  design: () => (<svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><polygon points="12 2 2 7 12 12 22 7 12 2" /><polyline points="2 17 12 22 22 17" /><polyline points="2 12 12 17 22 12" /></svg>),
  create: () => (<svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v18M3 12h18" /><circle cx="12" cy="12" r="10" /></svg>),
  analyze: () => (<svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /><path d="M10 8v6M7 11h6" /></svg>),
  paste: () => (<svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M16 4h2a2 2 0 012 2v14a2 2 0 01-2 2H6a2 2 0 01-2-2V6a2 2 0 012-2h2" /><rect x="8" y="2" width="8" height="4" rx="1" /><path d="M9 14l2 2 4-4" /></svg>),
  bolt: () => (<svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z" /></svg>),
  arrow: () => (<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12h14M12 5l7 7-7 7" /></svg>),
  copy: () => (<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" /><path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1" /></svg>),
  back: () => (<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M19 12H5M12 19l-7-7 7-7" /></svg>),
  skip: () => (<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="5 4 15 12 5 20 5 4" /><line x1="19" y1="5" x2="19" y2="19" /></svg>),
  refresh: () => (<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="23 4 23 10 17 10" /><path d="M20.49 15a9 9 0 11-2.12-9.36L23 10" /></svg>),
  edit: () => (<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M17 3a2.828 2.828 0 114 4L7.5 20.5 2 22l1.5-5.5L17 3z" /></svg>),
  zap: () => (<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z" /></svg>),
  book: () => (<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M2 3h6a4 4 0 014 4v14a3 3 0 00-3-3H2z" /><path d="M22 3h-6a4 4 0 00-4 4v14a3 3 0 013-3h7z" /></svg>),
  mic: () => (<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 1a3 3 0 00-3 3v8a3 3 0 006 0V4a3 3 0 00-3-3z"/><path d="M19 10v2a7 7 0 01-14 0v-2"/><line x1="12" y1="19" x2="12" y2="23"/><line x1="8" y1="23" x2="16" y2="23"/></svg>),
  micOn: () => (<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 1a3 3 0 00-3 3v8a3 3 0 006 0V4a3 3 0 00-3-3z" fill="currentColor"/><path d="M19 10v2a7 7 0 01-14 0v-2"/><line x1="12" y1="19" x2="12" y2="23"/><line x1="8" y1="23" x2="16" y2="23"/></svg>),
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
declare global { interface Window { SpeechRecognition: any; webkitSpeechRecognition: any; } }

// ── Voice Input (Web Speech API) ──
const VoiceBtn = ({onResult}: {onResult: (t: string) => void}) => {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const [on,setOn]=useState(false); const recRef=useRef<any>(null);
  const toggle=()=>{
    if(on){recRef.current?.stop();setOn(false);return;}
    const SR=window.SpeechRecognition||window.webkitSpeechRecognition;
    if(!SR){alert("お使いのブラウザは音声入力に対応していません");return;}
    const r=new SR();r.lang="ja-JP";r.continuous=true;r.interimResults=true;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    r.onresult=(e: any)=>{let t="";for(let i=0;i<e.results.length;i++)t+=e.results[i][0].transcript;onResult(t);};
    r.onerror=()=>setOn(false);r.onend=()=>setOn(false);
    r.start();recRef.current=r;setOn(true);
  };
  return(<button onClick={toggle} style={{position:"absolute",right:12,bottom:12,padding:on?"8px 14px":"8px 12px",borderRadius:10,border:on?"1.5px solid rgba(239,68,68,0.6)":"1.5px solid rgba(74,222,128,0.25)",background:on?"rgba(239,68,68,0.12)":"rgba(74,222,128,0.06)",color:on?"#f87171":"#4ade80",cursor:"pointer",transition:"all 0.3s",display:"flex",alignItems:"center",gap:6,fontSize:"0.8rem",fontWeight:500,boxShadow:on?"0 0 12px rgba(239,68,68,0.2)":"0 0 8px rgba(74,222,128,0.08)",animation:on?"pulse 1.5s infinite":"none"}}>{on?<><Icon.micOn/> 録音中...</>:<><Icon.mic/> 音声入力</>}</button>);
};
const TA=({value,onChange,style,placeholder,minH}: {value: string; onChange: (v: string) => void; style?: React.CSSProperties; placeholder?: string; minH?: number})=>(<div style={{position:"relative"}}><textarea style={{...S.ta,minHeight:minH||110,...style}} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/><VoiceBtn onResult={t=>onChange(value?value+"\n"+t:t)}/></div>);

const Particles = () => {
  const ref = useRef<HTMLCanvasElement>(null); const mouse = useRef({ x: -1000, y: -1000 });
  useEffect(() => {
    const c = ref.current; if (!c) return; const ctx = c.getContext("2d"); if (!ctx) return; let w: number, h: number, animId: number;
    const resize = () => { w = c.width = window.innerWidth; h = c.height = window.innerHeight; }; resize(); window.addEventListener("resize", resize);
    const dots = Array.from({ length: 180 }, () => ({ x: Math.random()*(w||800), y: Math.random()*(h||600), vx: (Math.random()-0.5)*0.5, vy: (Math.random()-0.5)*0.5, size: Math.random()*2.5+0.5, op: Math.random()*0.6+0.2, hue: Math.random()*50+145, ph: Math.random()*Math.PI*2 }));
    const onM = (e: MouseEvent) => { mouse.current = { x: e.clientX, y: e.clientY }; }; window.addEventListener("mousemove", onM);
    let t = 0; const loop = () => { t += 0.008; ctx.clearRect(0,0,w,h); const mx=mouse.current.x, my=mouse.current.y;
      dots.forEach((p,i) => { const dx=p.x-mx, dy=p.y-my, dist=Math.sqrt(dx*dx+dy*dy), R=180; if(dist<R&&dist>0){const f=((R-dist)/R)*1.2,a=Math.atan2(dy,dx);p.vx+=Math.cos(a)*f;p.vy+=Math.sin(a)*f;} p.vx+=Math.sin(t+p.ph)*0.01;p.vy+=Math.cos(t+p.ph*1.3)*0.01;p.vx*=0.955;p.vy*=0.955;p.x+=p.vx;p.y+=p.vy; if(p.x<-20)p.x=w+20;if(p.x>w+20)p.x=-20;if(p.y<-20)p.y=h+20;if(p.y>h+20)p.y=-20; const glow=dist<R?1.5+((R-dist)/R)*2:1,br=0.7+Math.sin(t*2+p.ph)*0.3,sz=p.size*glow,op=Math.min(p.op*glow*br,1); if(dist<R){ctx.beginPath();ctx.arc(p.x,p.y,sz*4,0,Math.PI*2);const g=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,sz*4);g.addColorStop(0,`hsla(${p.hue},90%,70%,${op*0.15})`);g.addColorStop(1,"transparent");ctx.fillStyle=g;ctx.fill();} ctx.beginPath();ctx.arc(p.x,p.y,sz,0,Math.PI*2);ctx.fillStyle=`hsla(${p.hue},85%,65%,${op})`;ctx.fill(); for(let j=i+1;j<dots.length;j++){const d=Math.hypot(p.x-dots[j].x,p.y-dots[j].y);if(d<90){ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(dots[j].x,dots[j].y);ctx.strokeStyle=`hsla(160,50%,55%,${0.12*(1-d/90)})`;ctx.lineWidth=0.4;ctx.stroke();}}
      }); animId=requestAnimationFrame(loop); }; loop();
    return () => { cancelAnimationFrame(animId); window.removeEventListener("resize",resize); window.removeEventListener("mousemove",onM); };
  }, []); return <canvas ref={ref} style={{ position:"fixed",inset:0,width:"100%",height:"100%",pointerEvents:"none",zIndex:0 }} />;
};
const Glitch = ({children}: {children: React.ReactNode}) => (<span style={{position:"relative",display:"inline-block"}}><span style={{position:"relative",zIndex:1}}>{children}</span><span style={{position:"absolute",top:0,left:0,color:"#06b6d4",clipPath:"inset(0 0 65% 0)",transform:"translate(2px,-1px)",opacity:0.4}}>{children}</span><span style={{position:"absolute",top:0,left:0,color:"#4ade80",clipPath:"inset(65% 0 0 0)",transform:"translate(-2px,1px)",opacity:0.4}}>{children}</span></span>);
const InteractiveTitle = () => {
  const text="プロンプトの限界を、超えろ。"; const[chars,setChars]=useState(text.split("").map(c=>({c,lit:false})));
  return(<div style={{margin:"16px auto 48px",textAlign:"center",userSelect:"none",cursor:"pointer"}} onMouseLeave={()=>setChars(p=>p.map(ch=>({...ch,lit:false})))}>
    {chars.map((ch,i)=>(<span key={i} onMouseEnter={()=>setChars(p=>p.map((c,j)=>({...c,lit:Math.abs(j-i)<=2})))} style={{fontSize:"clamp(1.8rem,4.5vw,3.2rem)",fontWeight:800,letterSpacing:"0.06em",display:"inline-block",color:ch.lit?"#4ade80":"#fff",textShadow:ch.lit?"0 0 20px rgba(74,222,128,0.8)":"0 0 30px rgba(74,222,128,0.15)",transform:ch.lit?"translateY(-6px) scale(1.15)":"translateY(0) scale(1)",transition:"all 0.25s cubic-bezier(0.16,1,0.3,1)",animation:`fadeUp 1s cubic-bezier(0.16,1,0.3,1) ${0.4+i*0.03}s both`}}>{ch.c}</span>))}
  </div>);
};
const CATS=[{id:"fix",label:"修正系",desc:"バグ修正・改善",Ic:Icon.fix},{id:"design",label:"設計系",desc:"仕様策定・デザイン",Ic:Icon.design},{id:"create",label:"制作系",desc:"コード・コンテンツ",Ic:Icon.create},{id:"analyze",label:"分析系",desc:"レビュー・比較",Ic:Icon.analyze}];
const PURPOSE_OPTIONS=["精度を上げたい","出力を具体的にしたい","フォーマットを整えたい","役割を明確にしたい","思考プロセスを改善したい","制約を追加したい","全体的に改善したい"];
const RULES_LABEL=["役割設定","目的分類","目的明確化","発動条件","現状整理","制約","思考プロセス","抽象度制御","PDCAループ","反証フェーズ","チェックリスト","例と非例","出力形式","情報不足時の対応"];
const CSS=`@import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&family=JetBrains+Mono:wght@400;500&family=Noto+Sans+JP:wght@300;400;500;600;700;800&display=swap');*{margin:0;padding:0;box-sizing:border-box}::-webkit-scrollbar{width:5px}::-webkit-scrollbar-thumb{background:rgba(74,222,128,0.2);border-radius:10px}@keyframes fadeUp{from{opacity:0;transform:translateY(24px)}to{opacity:1;transform:translateY(0)}}@keyframes fadeIn{from{opacity:0}to{opacity:1}}@keyframes slideIn{from{opacity:0;transform:translateX(-12px)}to{opacity:1;transform:translateX(0)}}@keyframes shimmer{0%{background-position:0% center}100%{background-position:200% center}}@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-8px)}}@keyframes scanline{0%{top:-10%}100%{top:110%}}@keyframes pulse{0%{transform:scale(0.95);opacity:0.6}50%{transform:scale(1.05);opacity:1}100%{transform:scale(0.95);opacity:0.6}}@keyframes pageIn{0%{opacity:0;transform:scale(0.95) translateY(20px)}100%{opacity:1;transform:scale(1) translateY(0)}}@keyframes cardFlash{0%{box-shadow:0 0 0 rgba(74,222,128,0)}40%{box-shadow:0 0 30px rgba(74,222,128,0.1)}100%{box-shadow:0 0 0 rgba(74,222,128,0)}}textarea:focus{border-color:rgba(74,222,128,0.5)!important;box-shadow:0 0 0 3px rgba(74,222,128,0.08)!important}@media(max-width:640px){.hero-modes{flex-direction:column!important;align-items:center!important}.hero-modes>button{width:100%!important;max-width:320px!important}.cat-grid{grid-template-columns:1fr!important}.r-wrap{padding:24px 14px!important}.r-card{padding:24px 18px!important}}`;
const S = {
  page:{minHeight:"100vh",background:"#060609",color:"#e4e4ec",fontFamily:"'Outfit','Noto Sans JP',sans-serif",position:"relative"} as React.CSSProperties,
  wrap:{maxWidth:720,margin:"0 auto",padding:"48px 20px",minHeight:"100vh",display:"flex",flexDirection:"column",justifyContent:"center",position:"relative",zIndex:2} as React.CSSProperties,
  card:{background:"rgba(255,255,255,0.02)",border:"1px solid rgba(255,255,255,0.06)",borderRadius:16,padding:36,backdropFilter:"blur(24px)",position:"relative",overflow:"hidden",animation:"pageIn 0.5s cubic-bezier(0.16,1,0.3,1),cardFlash 0.7s ease-out"} as React.CSSProperties,
  scan:{position:"absolute",top:0,left:0,right:0,height:1,background:"linear-gradient(90deg,transparent,rgba(74,222,128,0.3),transparent)",animation:"scanline 4s linear infinite",pointerEvents:"none"} as React.CSSProperties,
  tag:{display:"inline-flex",alignItems:"center",gap:6,padding:"5px 14px",borderRadius:6,fontSize:"0.72rem",fontWeight:600,background:"rgba(74,222,128,0.08)",color:"#4ade80",letterSpacing:"0.12em",textTransform:"uppercase" as const,marginBottom:14,border:"1px solid rgba(74,222,128,0.12)"},
  h2:{fontSize:"1.6rem",fontWeight:700,color:"#fff",marginBottom:20,lineHeight:1.35},
  ta:{width:"100%",minHeight:110,background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.08)",borderRadius:10,color:"#e4e4ec",fontSize:"0.95rem",padding:"14px 16px",resize:"vertical" as const,outline:"none",fontFamily:"'Outfit','Noto Sans JP',sans-serif",lineHeight:1.65,transition:"all 0.3s",boxSizing:"border-box" as const},
  btn:{display:"inline-flex",alignItems:"center",gap:8,padding:"13px 28px",fontSize:"0.92rem",fontWeight:600,background:"linear-gradient(135deg,#4ade80,#06b6d4)",color:"#060609",border:"none",borderRadius:10,cursor:"pointer",transition:"all 0.25s"},
  sec:{display:"inline-flex",alignItems:"center",gap:8,padding:"13px 28px",fontSize:"0.92rem",fontWeight:500,background:"transparent",color:"#9a9ab0",border:"1px solid rgba(255,255,255,0.08)",borderRadius:10,cursor:"pointer"},
  sm:{display:"inline-flex",alignItems:"center",gap:6,padding:"9px 18px",fontSize:"0.82rem",fontWeight:500,background:"rgba(255,255,255,0.02)",color:"#6a6a80",border:"1px solid rgba(255,255,255,0.05)",borderRadius:8,cursor:"pointer",transition:"all 0.25s"},
  opt:(on: boolean): React.CSSProperties=>({padding:"14px 18px",borderRadius:10,cursor:"pointer",transition:"all 0.25s",background:on?"rgba(74,222,128,0.08)":"rgba(255,255,255,0.02)",border:on?"1px solid rgba(74,222,128,0.35)":"1px solid rgba(255,255,255,0.06)",color:on?"#4ade80":"#b0b0c0",fontWeight:500,fontSize:"0.9rem",display:"flex",alignItems:"center",gap:10}),
  dot:(on: boolean): React.CSSProperties=>({width:8,height:8,borderRadius:"50%",flexShrink:0,background:on?"#4ade80":"transparent",border:on?"2px solid #4ade80":"2px solid rgba(255,255,255,0.15)",transition:"all 0.25s"}),
  code:{background:"rgba(0,0,0,0.5)",border:"1px solid rgba(255,255,255,0.06)",borderRadius:10,padding:20,fontFamily:"'JetBrains Mono',monospace",fontSize:"0.85rem",lineHeight:1.75,whiteSpace:"pre-wrap" as const,maxHeight:440,overflowY:"auto" as const,color:"#b8b8d0"},
};
const Shell=({children,out}: {children: React.ReactNode; out?: boolean})=>(<div style={S.page}><style>{CSS}</style><Particles /><div style={out?{transition:"all 0.3s",opacity:0,transform:"scale(1.05)"}:{}}>{children}</div></div>);
const Card=({children}: {children: React.ReactNode})=>(<div className="r-wrap" style={S.wrap}><div className="r-card" style={S.card}><div style={S.scan}/>{children}</div></div>);
const Loader=({text}: {text: string})=>(<div style={{textAlign:"center",padding:60}}><div style={{color:"#4ade80",animation:"pulse 1.5s infinite",display:"flex",alignItems:"center",justifyContent:"center",gap:8}}><Icon.zap/> {text}</div></div>);
const DiagSection=({color,icon,label,items,fA,fB}: {color: string; icon: string; label: string; items?: Array<Record<string,string>>; fA: string; fB: string})=>{if(!items?.length)return null;return(<div style={{marginBottom:16}}><div style={{fontSize:"0.82rem",color,fontWeight:600,marginBottom:8,display:"flex",alignItems:"center",gap:6}}>{icon} {label}</div>{items.map((it,i)=>(<div key={i} style={{padding:"10px 14px",background:`${color}11`,borderRadius:10,marginBottom:6,borderLeft:`3px solid ${color}55`,animation:`fadeUp 0.3s ease ${i*0.05}s both`}}><div style={{fontSize:"0.88rem",color:"#d0d0e0",fontWeight:500}}>{it[fA]}</div><div style={{fontSize:"0.78rem",color:"#9a9ab0",marginTop:2}}>{it[fB]}</div></div>))}</div>);};

interface AiQuestion { rule: string; question: string; type: string; options?: string[]; placeholder?: string; }
interface DiagResult { ok: Array<{point: string; reason: string}>; missing: Array<{point: string; suggestion: string}>; unclear: Array<{point: string; suggestion: string}>; questions: Array<{question: string; options: string[]}>; summary: string; }
interface ImprovResult { improved: string; changes: Array<{location: string; before: string; after: string; reason: string}>; problems: string[]; }

export default function PromptRefiner(){
  const[phase,setPhase]=useState("hero");const[mode,setMode]=useState<string|null>(null);const[cat,setCat]=useState<string|null>(null);const[goal,setGoal]=useState("");const[prompt,setPrompt]=useState("");const[result,setResult]=useState("");const[loading,setLoading]=useState(false);const[editing,setEditing]=useState(false);const[editBuf,setEditBuf]=useState("");const[copied,setCopied]=useState(false);const[error,setError]=useState("");const[sel,setSel]=useState<string|null>(null);const[aKey,setAKey]=useState(0);const[exiting,setExiting]=useState(false);const[textInput,setTextInput]=useState("");
  const[diag,setDiag]=useState<DiagResult|null>(null);const[explain,setExplain]=useState("");const[showExplain,setShowExplain]=useState(false);const[dqi,setDqi]=useState(0);const[dqSel,setDqSel]=useState<string|null>(null);const[dAns,setDAns]=useState<Record<string,string>>({});const[showDQ,setShowDQ]=useState(false);const[purpose,setPurpose]=useState<string|null>(null);const[improv,setImprov]=useState<ImprovResult|null>(null);
  const[aiQ,setAiQ]=useState<AiQuestion[]>([]);const[aiIdx,setAiIdx]=useState(0);const[aiAns,setAiAns]=useState<Record<string,string>>({});const[genSummary,setGenSummary]=useState("");const[feedback,setFeedback]=useState("");
  const go=(p: string)=>{setExiting(true);setTimeout(()=>{setExiting(false);setAKey(k=>k+1);setPhase(p);},300);};
  const ok=(t: string)=>{if(!t||t.trim().length<2){setError("入力してください");return false;}setError("");return true;};
  const reset=()=>{setMode(null);setCat(null);setGoal("");setPrompt("");setResult("");setEditing(false);setError("");setSel(null);setTextInput("");setDiag(null);setExplain("");setShowExplain(false);setDqi(0);setDqSel(null);setDAns({});setShowDQ(false);setPurpose(null);setImprov(null);setAiQ([]);setAiIdx(0);setAiAns({});setGenSummary("");setFeedback("");go("hero");};
  const doCopy=()=>{navigator.clipboard.writeText(editing?editBuf:result);setCopied(true);setTimeout(()=>setCopied(false),2000);};

  const callAPI=async(system: string|null, userMsg: string, maxTok=2000)=>{
    const res=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({system,message:userMsg,maxTokens:maxTok})});
    const data=await res.json();
    if(data.error) throw new Error(data.error);
    return data.text||"";
  };

  const apiGenQ=async()=>{if(!ok(goal))return;setLoading(true);go("genQ");try{const txt=await callAPI(`プロンプトエンジニアリング専門家。14ルール順で質問生成。\n【順番】${RULES_LABEL.join("→")}\n【ルール】重要なルールだけ5〜8問。抽象→具体の順。type:"select"=選択肢、type:"text"=自由入力(コード,URL,参考情報)。必要に応じて参考画像やコードの質問も入れる。この目的に特化した具体的質問。JSON配列のみ。\n[{"rule":"ルール名","question":"質問","type":"select","options":["A","B","C"]},{"rule":"ルール名","question":"質問","type":"text","placeholder":"例"}]`,`カテゴリ：${CATS.find(c=>c.id===cat)?.label}\n目的：${goal}`);setAiQ(JSON.parse(txt.replace(/```json|```/g,"").trim()));setAiIdx(0);setAiAns({});}catch{setAiQ([{rule:"目的明確化",question:"もう少し具体的に教えてください",type:"text",placeholder:"詳細..."}]);}setLoading(false);};
  const apiGenSummary=async()=>{setLoading(true);go("genConfirm");try{setGenSummary(await callAPI(`回答をもとに「つまり、あなたがやりたいのは〜ということですね？」形式で5-8行要約。具体的に。`,`カテゴリ：${CATS.find(c=>c.id===cat)?.label}\n目的：${goal}\n回答：\n${Object.entries(aiAns).map(([k,v])=>`${k}: ${v}`).join("\n")}`));}catch{setGenSummary(`やりたいのは「${goal}」ですね？`);}setLoading(false);};
  const apiGenerate=async()=>{setLoading(true);go("result");try{const txt=await callAPI(`プロンプトエンジニアリング最高専門家。14ルール完全準拠で最高品質プロンプト生成。全回答反映。マークダウン出力。${feedback?`\nユーザー修正：${feedback}`:""}`,`【カテゴリ】${CATS.find(c=>c.id===cat)?.label}\n【目的】${goal}\n【回答】\n${Object.entries(aiAns).map(([k,v])=>`${k}: ${v}`).join("\n")}`,4000);setResult(txt);setEditBuf(txt);setImprov(null);}catch{setResult("APIエラーが発生しました。しばらく待ってから再度お試しください。");}setLoading(false);};
  const runDiag=async(text: string)=>{setLoading(true);go("diagResult");try{const txt=await callAPI(`プロンプト診断AI。14ルール診断。JSONのみ。\n{"ok":[{"point":"良い点","reason":"理由"}],"missing":[{"point":"足りない","suggestion":"追加すべき"}],"unclear":[{"point":"曖昧","suggestion":"明確にすべき"}],"questions":[{"question":"補完質問","options":["A","B","C"]}],"summary":"総評"}\nquestions最大5問。`,text);setDiag(JSON.parse(txt.replace(/```json|```/g,"").trim()));}catch{setDiag({ok:[],missing:[],unclear:[],questions:[],summary:"診断失敗。しばらく待ってから再度お試しください。"});}setLoading(false);};
  const apiDiag=()=>{if(!ok(prompt))return;runDiag(prompt);};
  const apiExplain=async()=>{setLoading(true);setShowExplain(true);try{setExplain(await callAPI(null,`プロンプトを初心者向けに解説。\n\n${prompt}`,1500));}catch{setExplain("エラーが発生しました。");}setLoading(false);};
  const apiImprove=async()=>{setLoading(true);try{const txt=await callAPI(`プロンプト改善専門家。14ルール基準。JSONのみ。\n{"improved":"改善全文","changes":[{"location":"箇所","before":"元","after":"改善後","reason":"理由"}],"problems":["問題点"]}`,`【元】\n${prompt}\n【目的】${purpose||"全体改善"}\n【診断】${JSON.stringify(diag)}\n【補完】${JSON.stringify(dAns)}`,4000);const p=JSON.parse(txt.replace(/```json|```/g,"").trim());setImprov(p);setResult(p.improved||"");setEditBuf(p.improved||"");go("result");}catch{setResult("APIエラーが発生しました。しばらく待ってから再度お試しください。");go("result");}setLoading(false);};
  const reDiag=()=>{const text=editing?editBuf:result;setPrompt(text);setDiag(null);setExplain("");setShowExplain(false);setDqi(0);setDqSel(null);setDAns({});setShowDQ(false);setPurpose(null);setImprov(null);setSel(null);setEditing(false);setMode("paste");runDiag(text);};

  if(phase==="hero")return(<Shell out={exiting}><div key={aKey} style={{height:"100vh",display:"flex",flexDirection:"column",justifyContent:"center",alignItems:"center",position:"relative",zIndex:2,animation:"pageIn 0.7s cubic-bezier(0.16,1,0.3,1)"}}><div style={{textAlign:"center"}}><div style={{...S.tag,animation:"pulse 2.5s infinite",marginBottom:28}}><Icon.zap/> PROMPT ENGINEERING SYSTEM</div><h1 style={{fontSize:"clamp(3rem,7vw,5.5rem)",fontWeight:900,background:"linear-gradient(135deg,#4ade80 0%,#06b6d4 40%,#4ade80 80%)",backgroundSize:"200% auto",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",letterSpacing:"-0.04em",lineHeight:1.05,marginBottom:"0.6rem",animation:"shimmer 4s linear infinite"}}><Glitch>PROMPT</Glitch><br/><Glitch>REFINER</Glitch></h1><InteractiveTitle/><div className="hero-modes" style={{display:"flex",gap:16,justifyContent:"center",flexWrap:"wrap"}}>{[{id:"paste",label:"プロンプトを入れる",desc:"診断→補完→改善",Ic:Icon.paste},{id:"gen",label:"一から生成する",desc:"AI質問で最強構築",Ic:Icon.bolt}].map((m,i)=>(<button key={m.id} style={{display:"flex",flexDirection:"column",alignItems:"center",gap:12,padding:"28px 36px",background:"rgba(255,255,255,0.02)",border:"1px solid rgba(255,255,255,0.06)",borderRadius:14,color:"#e4e4ec",cursor:"pointer",transition:"all 0.35s",minWidth:200,animation:`fadeUp 0.6s ease ${0.6+i*0.15}s both`}} onMouseEnter={e=>{e.currentTarget.style.borderColor="rgba(74,222,128,0.35)";e.currentTarget.style.background="rgba(74,222,128,0.04)";e.currentTarget.style.transform="translateY(-4px)";}} onMouseLeave={e=>{e.currentTarget.style.borderColor="rgba(255,255,255,0.06)";e.currentTarget.style.background="rgba(255,255,255,0.02)";e.currentTarget.style.transform="translateY(0)";}} onClick={()=>{setMode(m.id);go(m.id==="paste"?"pasteInput":"category");}}><div style={{color:"#4ade80",animation:"float 3s ease-in-out infinite"}}><m.Ic/></div><div style={{fontWeight:700,fontSize:"1.05rem"}}>{m.label}</div><div style={{fontSize:"0.78rem",color:"#6a6a80"}}>{m.desc}</div></button>))}</div></div></div></Shell>);

  if(phase==="pasteInput")return(<Shell out={exiting}><Card><div style={S.tag}>CHECK & IMPROVE</div><h2 style={S.h2}>プロンプトを貼り付けてください</h2><TA value={prompt} onChange={v=>{setPrompt(v);setError("");}} placeholder="プロンプトをここに..." minH={200}/>{error&&<div style={{marginTop:8,padding:"10px 14px",borderRadius:8,background:"rgba(239,68,68,0.08)",border:"1px solid rgba(239,68,68,0.2)",color:"#f87171",fontSize:"0.85rem"}}>{error}</div>}<div style={{display:"flex",justifyContent:"space-between",marginTop:20}}><button style={S.sec} onClick={reset}><Icon.back/> 戻る</button><button style={S.btn} onClick={apiDiag}>チェック開始 <Icon.arrow/></button></div></Card></Shell>);

  if(phase==="diagResult"){const qs=diag?.questions||[];return(<Shell out={exiting}><Card><div style={S.tag}>DIAGNOSIS</div>{loading?<Loader text="チェック中..."/>:diag?(<><div style={{...S.code,marginBottom:20}}>{diag.summary}</div><DiagSection color="#4ade80" icon="✓" label="ここはOK" items={diag.ok as unknown as Array<Record<string,string>>} fA="point" fB="reason"/><DiagSection color="#f87171" icon="✗" label="足りていない" items={diag.missing as unknown as Array<Record<string,string>>} fA="point" fB="suggestion"/><DiagSection color="#fbbf24" icon="!" label="曖昧・不明確" items={diag.unclear as unknown as Array<Record<string,string>>} fA="point" fB="suggestion"/>{showExplain&&explain&&<div style={{...S.code,marginBottom:16,borderColor:"rgba(6,182,212,0.2)"}}>{explain}</div>}{!purpose&&(<div style={{marginBottom:20,padding:20,background:"rgba(74,222,128,0.03)",border:"1px solid rgba(74,222,128,0.12)",borderRadius:12}}><div style={{fontSize:"0.88rem",color:"#fff",fontWeight:600,marginBottom:12}}>このプロンプトで何をしたい？</div><div style={{display:"flex",flexDirection:"column",gap:6}}>{PURPOSE_OPTIONS.map((p,i)=><div key={i} style={S.opt(sel===p)} onClick={()=>setSel(p)}><div style={S.dot(sel===p)}/>{p}</div>)}</div><button style={{...S.btn,marginTop:12,width:"100%",justifyContent:"center",opacity:sel?1:0.35,pointerEvents:sel?"auto":"none"}} onClick={()=>{setPurpose(sel);setSel(null);}}>決定 <Icon.arrow/></button></div>)}{purpose&&qs.length>0&&showDQ&&dqi<qs.length&&(<div style={{marginBottom:20,padding:20,background:"rgba(6,182,212,0.04)",border:"1px solid rgba(6,182,212,0.15)",borderRadius:12}}><div style={{fontSize:"0.82rem",color:"#06b6d4",fontWeight:600,marginBottom:12}}>補完質問（{dqi+1}/{qs.length}）</div><h3 style={{fontSize:"1.1rem",color:"#fff",fontWeight:600,marginBottom:14}}>{qs[dqi]?.question}</h3><div style={{display:"flex",flexDirection:"column",gap:6}}>{qs[dqi]?.options?.map((o,i)=><div key={i} style={S.opt(dqSel===o)} onClick={()=>setDqSel(o)}><div style={S.dot(dqSel===o)}/>{o}</div>)}</div><div style={{display:"flex",gap:8,marginTop:12}}><button style={{...S.btn,flex:1,opacity:dqSel?1:0.35,pointerEvents:dqSel?"auto":"none"}} onClick={()=>{setDAns(p=>({...p,[qs[dqi].question]:dqSel!}));setDqi(dqi+1);setDqSel(null);}}>次へ <Icon.arrow/></button><button style={S.sm} onClick={()=>{setDAns(p=>({...p,[qs[dqi].question]:"スキップ"}));setDqi(dqi+1);setDqSel(null);}}><Icon.skip/> スキップ</button></div></div>)}<div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{!showExplain&&<button style={S.sm} onClick={apiExplain}><Icon.book/> 意味を解説</button>}{purpose&&qs.length>0&&!showDQ&&<button style={{...S.sm,color:"#06b6d4",borderColor:"rgba(6,182,212,0.2)"}} onClick={()=>setShowDQ(true)}><Icon.zap/> 質問で補完</button>}{purpose&&<button style={{...S.btn,flex:1,justifyContent:"center"}} onClick={apiImprove} disabled={loading}>{loading?"改善中...":"改善版を生成"}</button>}<button style={S.sm} onClick={reset}><Icon.refresh/> 最初から</button></div></>):null}</Card></Shell>);}

  if(phase==="category")return(<Shell out={exiting}><Card><div style={S.tag}>STEP 01</div><h2 style={S.h2}>何をしたいですか？</h2><div className="cat-grid" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>{CATS.map((c,i)=>(<button key={c.id} style={{padding:"22px 16px",textAlign:"center",background:cat===c.id?"rgba(74,222,128,0.06)":"rgba(255,255,255,0.015)",border:cat===c.id?"1px solid rgba(74,222,128,0.3)":"1px solid rgba(255,255,255,0.05)",borderRadius:12,cursor:"pointer",color:"#e4e4ec",transition:"all 0.3s",animation:`fadeUp 0.4s ease ${i*0.08}s both`}} onClick={()=>setCat(c.id)}><div style={{color:cat===c.id?"#4ade80":"#6a6a80",marginBottom:8}}><c.Ic/></div><div style={{fontWeight:600,fontSize:"0.95rem",marginBottom:4}}>{c.label}</div><div style={{fontSize:"0.78rem",color:"#6a6a80"}}>{c.desc}</div></button>))}</div><div style={{display:"flex",justifyContent:"space-between",marginTop:24}}><button style={S.sec} onClick={reset}><Icon.back/> 戻る</button>{cat&&<button style={{...S.btn,animation:"fadeIn 0.3s"}} onClick={()=>go("genInput")}>次へ <Icon.arrow/></button>}</div></Card></Shell>);

  if(phase==="genInput")return(<Shell out={exiting}><Card><div style={S.tag}>STEP 02</div><h2 style={S.h2}>目的を教えてください</h2><p style={{color:"#6a6a80",fontSize:"0.85rem",marginBottom:16}}>ざっくりでOK。ここから質問で具体化していきます</p><TA value={goal} onChange={v=>{setGoal(v);setError("");}} placeholder="例：現代的でダイナミックな動きのあるWebサイトを作りたい"/>{error&&<div style={{marginTop:8,padding:"10px 14px",borderRadius:8,background:"rgba(239,68,68,0.08)",border:"1px solid rgba(239,68,68,0.2)",color:"#f87171",fontSize:"0.85rem"}}>{error}</div>}<div style={{display:"flex",justifyContent:"space-between",marginTop:16}}><button style={S.sec} onClick={()=>go("category")}><Icon.back/> 戻る</button><button style={S.btn} onClick={apiGenQ}>質問を生成 <Icon.arrow/></button></div></Card></Shell>);

  if(phase==="genQ"){const q=aiQ[aiIdx],total=aiQ.length,pct=total>0?(aiIdx/total)*100:0,done=aiIdx>=total;
    if(loading)return(<Shell out={exiting}><Card><Loader text="あなたに最適な質問を生成中..."/></Card></Shell>);
    if(done)return(<Shell out={exiting}><Card><div style={S.tag}>READY</div><h2 style={S.h2}>質問完了！</h2><p style={{color:"#9a9ab0",marginBottom:20}}>回答をもとに確認画面へ進みます。</p><div style={{display:"flex",gap:10}}><button style={S.sec} onClick={()=>setAiIdx(0)}><Icon.back/> やり直す</button><button style={{...S.btn,flex:1,justifyContent:"center"}} onClick={apiGenSummary}>確認へ <Icon.arrow/></button></div></Card></Shell>);
    if(!q)return null;const isText=q.type==="text";
    return(<Shell out={exiting}><Card><div style={{width:"100%",height:3,background:"rgba(255,255,255,0.04)",borderRadius:2,marginBottom:28,overflow:"hidden"}}><div style={{width:`${pct}%`,height:"100%",background:"linear-gradient(90deg,#4ade80,#06b6d4)",borderRadius:2,transition:"width 0.6s"}}/></div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><div style={{...S.tag,background:"rgba(6,182,212,0.08)",color:"#06b6d4",borderColor:"rgba(6,182,212,0.15)"}}>{q.rule}</div><span style={{fontSize:"0.75rem",color:"#4a4a60",fontFamily:"'JetBrains Mono',monospace"}}>{String(aiIdx+1).padStart(2,"0")} / {String(total).padStart(2,"0")}</span></div><h2 style={{...S.h2,fontSize:"1.3rem",animation:"slideIn 0.4s ease"}}>{q.question}</h2>
    {isText?(<TA value={textInput} onChange={v=>setTextInput(v)} placeholder={q.placeholder||"入力..."} minH={100}/>):(<div style={{display:"flex",flexDirection:"column",gap:8,marginBottom:20}}>{q.options?.map((o,i)=>(<div key={i} style={{...S.opt(sel===o),animation:`fadeUp 0.3s ease ${i*0.05}s both`}} onClick={()=>setSel(o)}><div style={S.dot(sel===o)}/>{o}</div>))}</div>)}
    <div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:isText?12:0}}><button style={{...S.btn,flex:"1 1 auto",opacity:(isText?textInput.trim():sel)?1:0.35,pointerEvents:(isText?textInput.trim():sel)?"auto":"none"}} onClick={()=>{const val=isText?textInput.trim():sel!;setAiAns(p=>({...p,[`${q.rule}: ${q.question}`]:val}));setAiIdx(aiIdx+1);setSel(null);setTextInput("");}}>次へ <Icon.arrow/></button><button style={S.sm} onClick={()=>{setAiAns(p=>({...p,[`${q.rule}: ${q.question}`]:"指定なし"}));setAiIdx(aiIdx+1);setSel(null);setTextInput("");}}><Icon.skip/> スキップ</button></div>
    <div style={{marginTop:14,paddingTop:14,borderTop:"1px solid rgba(255,255,255,0.04)"}}><button style={{...S.sec,width:"100%",justifyContent:"center",fontSize:"0.85rem"}} onClick={apiGenSummary}><Icon.zap/> ここまでで確認へ</button></div></Card></Shell>);}

  if(phase==="genConfirm")return(<Shell out={exiting}><Card><div style={S.tag}>CONFIRM</div><h2 style={S.h2}>つまり、こういうことですか？</h2>{loading?<Loader text="まとめています..."/>:(<><div style={{...S.code,marginBottom:20}}>{genSummary}</div><div style={{marginBottom:16}}><p style={{color:"#6a6a80",fontSize:"0.85rem",marginBottom:8}}>違う部分があれば教えてください（任意）</p><TA value={feedback} onChange={v=>setFeedback(v)} placeholder="例：色はダーク系がいい、もっとミニマルな感じで..." minH={70}/></div><div style={{display:"flex",gap:10}}><button style={S.sec} onClick={()=>{setAiIdx(0);go("genQ");}}><Icon.back/> 質問やり直し</button><button style={{...S.btn,flex:1,justifyContent:"center"}} onClick={apiGenerate}>これで生成 <Icon.arrow/></button></div></>)}</Card></Shell>);

  if(phase==="result")return(<Shell out={exiting}><Card><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:16}}><div><div style={S.tag}>GENERATED</div><h2 style={{...S.h2,marginBottom:0}}>{mode==="paste"?"改善されたプロンプト":"生成されたプロンプト"}</h2></div><button style={{...S.sm,color:copied?"#4ade80":"#6a6a80"}} onClick={doCopy}><Icon.copy/> {copied?"Copied!":"コピー"}</button></div>{loading?<Loader text="生成中..."/>:editing?(<TA value={editBuf} onChange={v=>setEditBuf(v)} placeholder="" minH={380} style={{fontFamily:"'JetBrains Mono',monospace",fontSize:"0.85rem"}}/>):(<div style={S.code}>{result}</div>)}{improv&&!editing&&(<>{improv.problems?.length>0&&(<div style={{marginTop:16}}><div style={{fontSize:"0.82rem",color:"#f87171",fontWeight:600,marginBottom:8}}>✗ 元の問題点</div>{improv.problems.map((p,i)=>(<div key={i} style={{padding:"8px 14px",background:"rgba(239,68,68,0.04)",borderRadius:8,marginBottom:4,fontSize:"0.85rem",color:"#b8b8d0",borderLeft:"3px solid rgba(239,68,68,0.3)"}}>{p}</div>))}</div>)}{improv.changes?.length>0&&(<div style={{marginTop:16}}><div style={{fontSize:"0.82rem",color:"#4ade80",fontWeight:600,marginBottom:8}}>✓ 修正した箇所</div>{improv.changes.map((c,i)=>(<div key={i} style={{padding:"12px 14px",background:"rgba(74,222,128,0.04)",borderRadius:10,marginBottom:6,borderLeft:"3px solid rgba(74,222,128,0.3)"}}><div style={{fontSize:"0.82rem",color:"#4ade80",fontWeight:600,marginBottom:4}}>{c.location}</div><div style={{display:"flex",gap:8,fontSize:"0.8rem",marginBottom:4,flexWrap:"wrap"}}><span style={{color:"#f87171",textDecoration:"line-through"}}>{c.before}</span><span style={{color:"#6a6a80"}}>→</span><span style={{color:"#4ade80"}}>{c.after}</span></div><div style={{fontSize:"0.75rem",color:"#6a6a80"}}>{c.reason}</div></div>))}</div>)}</>)}<div style={{display:"flex",gap:8,marginTop:18,flexWrap:"wrap"}}><button style={S.sm} onClick={()=>{setEditing(!editing);if(!editing)setEditBuf(result);}}><Icon.edit/> {editing?"プレビュー":"編集"}</button><button style={{...S.sm,color:"#06b6d4",borderColor:"rgba(6,182,212,0.2)"}} onClick={reDiag}><Icon.zap/> この結果を再診断</button><button style={S.sm} onClick={reset}><Icon.refresh/> 最初から</button><button style={{...S.btn,flex:1,justifyContent:"center"}} onClick={()=>{if(editing){setResult(editBuf);setEditing(false);}else{mode==="paste"?apiImprove():apiGenerate();}}}>{editing?"保存":"再生成"}</button></div></Card></Shell>);

  return null;
}
